import React, { useEffect } from 'react'
import { Button, Table } from 'antd'
import { useState } from 'react'
import AddGoods from '../addGoods'
import { clone } from 'ramda'
import { TableData } from './utils'
import { useStateClassOperate } from '@/utils'

const testData = [
  {
    isRecommend: 0,
    marketPrice: 499.7,
    goodsNameEn: null,
    goodsId: 1573087739994,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName: '12inches Deep Wave Full Lace Wig Pre Bleached Knots',
    actualSales: 0,
    productStockWarningState: null,
    productId: 30244151591002,
    categoryPath: 'Other1->Other2->Other',
    goodsStock: 0,
    categoryId1: 1471,
    categoryId2: 1472,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/oFUXc3exGebmdo513wW.jpg',
    categoryId3: 1473,
    goodsBriefEn: null,
    createTime: '2018-11-23 22:07:34',
    goodsPrice: 149.9,
    productList: [
      {
        productId: 30244151591002,
        specValues: 'Deep Wave,10 inches',
        goodsId: 1573087739994,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 200,
        barCode: 'FLW1028',
        isDefault: 1,
        mainImage: null,
        productCode: 'FLW1028',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,10 inches',
        goodsName: '12inches Deep Wave Full Lace Wig Pre Bleached Knots',
        mainImageUrl: null,
        productPrice: 149.9,
        height: 0
      },
      {
        productId: 15431561969754,
        specValues: 'Deep Wave,12 inches',
        goodsId: 1573087739994,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 200,
        barCode: 'FLW1028',
        isDefault: 0,
        mainImage: null,
        productCode: 'FLW1029',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,12 inches',
        goodsName: '12inches Deep Wave Full Lace Wig Pre Bleached Knots',
        mainImageUrl: null,
        productPrice: 164.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 249.75,
    goodsNameEn: null,
    goodsId: 6647771660378,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName:
      '12inches Mix Color Highlights Bob Wig Headband Wig (Get Free Trendy Headbands)',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39588545724506,
    categoryPath: 'Wigs->Weave Wigs->Headband Wig',
    goodsStock: 0,
    categoryId1: 1431,
    categoryId2: 1436,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/7WMsXiEMWOp3pZXfZI7.jpg',
    categoryId3: 1462,
    goodsBriefEn: null,
    createTime: '2021-10-25 16:06:21',
    goodsPrice: 109.9,
    productList: [
      {
        productId: 39588545724506,
        specValues: '12 inches',
        goodsId: 6647771660378,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 250,
        barCode: 'FLW1028',
        isDefault: 1,
        mainImage: null,
        productCode: 'mixc227hbobhdw012',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName:
          '12inches Mix Color Highlights Bob Wig Headband Wig (Get Free Trendy Headbands)',
        mainImageUrl: null,
        productPrice: 109.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 974.75,
    goodsNameEn: null,
    goodsId: 6740328710234,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 4,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName:
      '13x4 Luxurious Blonde Highlights Loose Wave Undetectable Lace Frontal Wig',
    actualSales: 5,
    productStockWarningState: null,
    productId: 39950176452698,
    categoryPath: 'Wigs->HD Lace Wigs->13x4 HD Frontal Lace Wig',
    goodsStock: 188,
    categoryId1: 1431,
    categoryId2: 1434,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/Mqp5AxrwmXSouPQraP5.jpg',
    categoryId3: 1444,
    goodsBriefEn: null,
    createTime: '2022-05-09 17:57:23',
    goodsPrice: 389.9,
    productList: [
      {
        productId: 39950176485466,
        specValues: '22 inches',
        goodsId: 6740328710234,
        productStockWarning: -1,
        productStock: 175,
        length: 0,
        weight: 0,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'hd134lbhlwulfw022',
        width: 0,
        warning: false,
        specValueIds: '22 inches',
        goodsName:
          '13x4 Luxurious Blonde Highlights Loose Wave Undetectable Lace Frontal Wig',
        mainImageUrl: null,
        productPrice: 429.9,
        height: 0
      },
      {
        productId: 39950176452698,
        specValues: '20 inches',
        goodsId: 6740328710234,
        productStockWarning: -1,
        productStock: 13,
        length: 0,
        weight: 0,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: 'hd134lbhlwulfw020',
        width: 0,
        warning: false,
        specValueIds: '20 inches',
        goodsName:
          '13x4 Luxurious Blonde Highlights Loose Wave Undetectable Lace Frontal Wig',
        mainImageUrl: null,
        productPrice: 389.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 549.75,
    goodsNameEn: null,
    goodsId: 6742794698842,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 2,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '13x4 Natural Loose Wave Side Part Glueless Frontal Lace Wig',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39957892923482,
    categoryPath: 'Wigs->Lace Wigs->13x4 Frontal Lace Wig',
    goodsStock: 226,
    categoryId1: 1431,
    categoryId2: 1435,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/LLfR2MLhXGBdW3rlfc3.jpg',
    categoryId3: 1458,
    goodsBriefEn: null,
    createTime: '2022-05-17 15:26:09',
    goodsPrice: 219.9,
    productList: [
      {
        productId: 39957892923482,
        specValues: '12 inches',
        goodsId: 6742794698842,
        productStockWarning: -1,
        productStock: 226,
        length: 0,
        weight: 200,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: '134nlwspgflw012',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName:
          '13x4 Natural Loose Wave Side Part Glueless Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 219.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 549.75,
    goodsNameEn: null,
    goodsId: 6721582137434,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName: '13x6 Sleek Bobiania Blunt Cut Frontal Bob Wig',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39877640028250,
    categoryPath: 'Wigs->Lace Wigs->13x6 Frontal Lace Wig',
    goodsStock: 0,
    categoryId1: 1431,
    categoryId2: 1435,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/W8f2Po0RoXeRc3uaSwv.jpg',
    categoryId3: 1456,
    goodsBriefEn: null,
    createTime: '2022-03-17 20:36:11',
    goodsPrice: 219.9,
    productList: [
      {
        productId: 39877640028250,
        specValues: '14 inches',
        goodsId: 6721582137434,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 1,
        mainImage: null,
        productCode: '136slkbbcutfrbob014',
        width: 0,
        warning: false,
        specValueIds: '14 inches',
        goodsName: '13x6 Sleek Bobiania Blunt Cut Frontal Bob Wig',
        mainImageUrl: null,
        productPrice: 219.9,
        height: 0
      },
      {
        productId: 39877639176282,
        specValues: '12 inches',
        goodsId: 6721582137434,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '136slkbbcutfrbob012',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName: '13x6 Sleek Bobiania Blunt Cut Frontal Bob Wig',
        mainImageUrl: null,
        productPrice: 189.9,
        height: 0
      },
      {
        productId: 39877639143514,
        specValues: '10 inches',
        goodsId: 6721582137434,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '136slkbbcutfrbob010',
        width: 0,
        warning: false,
        specValueIds: '10 inches',
        goodsName: '13x6 Sleek Bobiania Blunt Cut Frontal Bob Wig',
        mainImageUrl: null,
        productPrice: 159.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 0,
    goodsNameEn: null,
    goodsId: 6736406020186,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName: '13x6 Sleek Bobiania Blunt Cut Frontal Bob Wig | Limited Size',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39936923107418,
    categoryPath: 'Wigs->Lace Wigs->13x6 Frontal Lace Wig',
    goodsStock: 22,
    categoryId1: 1431,
    categoryId2: 1435,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/pBfwMpIeOGBsEwIizdq.jpg',
    categoryId3: 1456,
    goodsBriefEn: null,
    createTime: '2022-04-28 18:01:44',
    goodsPrice: 139.9,
    productList: [
      {
        productId: 39936923107418,
        specValues: '14inches',
        goodsId: 6736406020186,
        productStockWarning: -1,
        productStock: 22,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: '136slkbbcutfrbob014',
        width: 0,
        warning: false,
        specValueIds: '14inches',
        goodsName:
          '13x6 Sleek Bobiania Blunt Cut Frontal Bob Wig | Limited Size',
        mainImageUrl: null,
        productPrice: 139.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 474.75,
    goodsNameEn: null,
    goodsId: 6727581499482,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName: '13x6 Straight Shoulder Length Lace Frontal Wig',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39900742647898,
    categoryPath: 'Wigs->Lace Wigs->13x6 Frontal Lace Wig',
    goodsStock: 0,
    categoryId1: 1431,
    categoryId2: 1435,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/nVixuBhnrEMpD5rdlrp.jpg',
    categoryId3: 1456,
    goodsBriefEn: null,
    createTime: '2022-04-02 14:25:44',
    goodsPrice: 189.9,
    productList: [
      {
        productId: 39900742647898,
        specValues: '16 inches',
        goodsId: 6727581499482,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: '136stsllacewig016',
        width: 0,
        warning: false,
        specValueIds: '16 inches',
        goodsName: '13x6 Straight Shoulder Length Lace Frontal Wig',
        mainImageUrl: null,
        productPrice: 189.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 324.75,
    goodsNameEn: null,
    goodsId: 6651774369882,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName:
      '14inches Deep Wave Affordable Headband Wig (Get Free Trendy Headband)',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39606409756762,
    categoryPath: 'Wigs->Weave Wigs->Headband Wig',
    goodsStock: 207,
    categoryId1: 1431,
    categoryId2: 1436,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/OB6nyXUexPGXLrdDm8p.jpg',
    categoryId3: 1462,
    goodsBriefEn: null,
    createTime: '2021-11-03 15:28:36',
    goodsPrice: 129.9,
    productList: [
      {
        productId: 39606409756762,
        specValues: '14 inches',
        goodsId: 6651774369882,
        productStockWarning: -1,
        productStock: 207,
        length: 0,
        weight: 250,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: 'dwahdbdw014',
        width: 0,
        warning: false,
        specValueIds: '14 inches',
        goodsName:
          '14inches Deep Wave Affordable Headband Wig (Get Free Trendy Headband)',
        mainImageUrl: null,
        productPrice: 129.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 374.75,
    goodsNameEn: null,
    goodsId: 6651921924186,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName:
      '16inches Jerry Curl Affordable Headband Wig (Get Free Trendy Headband)',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39608868241498,
    categoryPath: 'Wigs->Weave Wigs->Headband Wig',
    goodsStock: 441,
    categoryId1: 1431,
    categoryId2: 1436,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/cOi4g3iRQNwu0Y7aGr3.jpg',
    categoryId3: 1462,
    goodsBriefEn: null,
    createTime: '2021-11-03 17:41:25',
    goodsPrice: 149.9,
    productList: [
      {
        productId: 39608868241498,
        specValues: '16 inches',
        goodsId: 6651921924186,
        productStockWarning: -1,
        productStock: 441,
        length: 0,
        weight: 250,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: 'jcahdbdw016',
        width: 0,
        warning: false,
        specValueIds: '16 inches',
        goodsName:
          '16inches Jerry Curl Affordable Headband Wig (Get Free Trendy Headband)',
        mainImageUrl: null,
        productPrice: 149.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 449.75,
    goodsNameEn: null,
    goodsId: 1611598921818,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 1,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
    actualSales: 0,
    productStockWarningState: null,
    productId: 15880251211866,
    categoryPath: 'Wigs->Lace Wigs->13x4 Frontal Lace Wig',
    goodsStock: 1274,
    categoryId1: 1431,
    categoryId2: 1435,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/ZWO6ompUvg2kS9wswEM.jpg',
    categoryId3: 1458,
    goodsBriefEn: null,
    createTime: '2018-12-22 11:29:57',
    goodsPrice: 179.9,
    productList: [
      {
        productId: 39755934531674,
        specValues: 'Straight,28 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw28',
        width: 0,
        warning: false,
        specValueIds: 'Straight,28 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 478.9,
        height: 0
      },
      {
        productId: 15880251244634,
        specValues: 'Straight,10 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 26,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw10',
        width: 0,
        warning: false,
        specValueIds: 'Straight,10 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 179.9,
        height: 0
      },
      {
        productId: 15880251211866,
        specValues: 'Body Wave,10 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 44,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: 'frontallwbw10',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,10 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 179.9,
        height: 0
      },
      {
        productId: 15880213889114,
        specValues: 'Straight,26 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 29,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw26',
        width: 0,
        warning: false,
        specValueIds: 'Straight,26 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 418.9,
        height: 0
      },
      {
        productId: 15880213856346,
        specValues: 'Straight,24 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 105,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw24',
        width: 0,
        warning: false,
        specValueIds: 'Straight,24 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 358.9,
        height: 0
      },
      {
        productId: 15880213823578,
        specValues: 'Straight,22 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 102,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw22',
        width: 0,
        warning: false,
        specValueIds: 'Straight,22 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 327.9,
        height: 0
      },
      {
        productId: 15880213790810,
        specValues: 'Straight,20 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 34,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw20',
        width: 0,
        warning: false,
        specValueIds: 'Straight,20 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 309.9,
        height: 0
      },
      {
        productId: 15880213758042,
        specValues: 'Straight,18 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 58,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw18',
        width: 0,
        warning: false,
        specValueIds: 'Straight,18 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 272.9,
        height: 0
      },
      {
        productId: 15880213725274,
        specValues: 'Straight,16 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 74,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw16',
        width: 0,
        warning: false,
        specValueIds: 'Straight,16 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 249.9,
        height: 0
      },
      {
        productId: 15880213692506,
        specValues: 'Straight,14 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 87,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw14',
        width: 0,
        warning: false,
        specValueIds: 'Straight,14 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 219.9,
        height: 0
      },
      {
        productId: 15880213659738,
        specValues: 'Straight,12 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 17,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwstw12',
        width: 0,
        warning: false,
        specValueIds: 'Straight,12 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 189.9,
        height: 0
      },
      {
        productId: 15880213626970,
        specValues: 'Body Wave,26 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 59,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw26',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,26 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 408.9,
        height: 0
      },
      {
        productId: 15880213594202,
        specValues: 'Body Wave,24 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 98,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw24',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,24 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 348.9,
        height: 0
      },
      {
        productId: 15880213561434,
        specValues: 'Body Wave,22 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 95,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw22',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,22 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 317.9,
        height: 0
      },
      {
        productId: 15880213528666,
        specValues: 'Body Wave,20 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 128,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw20',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,20 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 299.9,
        height: 0
      },
      {
        productId: 15880213495898,
        specValues: 'Body Wave,18 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 99,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw18',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,18 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 262.9,
        height: 0
      },
      {
        productId: 15880213463130,
        specValues: 'Body Wave,16 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 124,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw16',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,16 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 239.9,
        height: 0
      },
      {
        productId: 15880213430362,
        specValues: 'Body Wave,14 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 80,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw14',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,14 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 219.9,
        height: 0
      },
      {
        productId: 15880212873306,
        specValues: 'Body Wave,12 inches',
        goodsId: 1611598921818,
        productStockWarning: -1,
        productStock: 15,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'frontallwbw12',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,12 inches',
        goodsName: '180% Density Frontal Lace Wig Glueless Pre Plucked',
        mainImageUrl: null,
        productPrice: 189.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 624.75,
    goodsNameEn: null,
    goodsId: 6673903878234,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName:
      '1B/27 New Fabulous Beyon-celebrity Style Ombre Frontal Lace Wig',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39705177063514,
    categoryPath: 'Other1->Other2->Other',
    goodsStock: 589,
    categoryId1: 1471,
    categoryId2: 1472,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/Jwwi2m2m7pOugkzLCc0.jpg',
    categoryId3: 1473,
    goodsBriefEn: null,
    createTime: '2021-12-15 14:57:33',
    goodsPrice: 249.9,
    productList: [
      {
        productId: 39705177161818,
        specValues: '22 inches',
        goodsId: 6673903878234,
        productStockWarning: -1,
        productStock: 148,
        length: 0,
        weight: 200,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'nfbcoflw22',
        width: 0,
        warning: false,
        specValueIds: '22 inches',
        goodsName:
          '1B/27 New Fabulous Beyon-celebrity Style Ombre Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 349.9,
        height: 0
      },
      {
        productId: 39705177129050,
        specValues: '20 inches',
        goodsId: 6673903878234,
        productStockWarning: -1,
        productStock: 147,
        length: 0,
        weight: 200,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'nfbcoflw20',
        width: 0,
        warning: false,
        specValueIds: '20 inches',
        goodsName:
          '1B/27 New Fabulous Beyon-celebrity Style Ombre Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 309.9,
        height: 0
      },
      {
        productId: 39705177096282,
        specValues: '18 inches',
        goodsId: 6673903878234,
        productStockWarning: -1,
        productStock: 147,
        length: 0,
        weight: 200,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: 'nfbcoflw18',
        width: 0,
        warning: false,
        specValueIds: '18 inches',
        goodsName:
          '1B/27 New Fabulous Beyon-celebrity Style Ombre Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 279.9,
        height: 0
      },
      {
        productId: 39705177063514,
        specValues: '16 inches',
        goodsId: 6673903878234,
        productStockWarning: -1,
        productStock: 147,
        length: 0,
        weight: 200,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: 'nfbcoflw16',
        width: 0,
        warning: false,
        specValueIds: '16 inches',
        goodsName:
          '1B/27 New Fabulous Beyon-celebrity Style Ombre Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 249.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 424.75,
    goodsNameEn: null,
    goodsId: 6666753441882,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName: '1B/27 Ombre Extented 4X4 Closure Lace Short Bob Wig',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39679460835418,
    categoryPath: 'Wigs->Lace Wigs->Extented 4x4 Closure Lace Wig',
    goodsStock: 0,
    categoryId1: 1431,
    categoryId2: 1435,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/pEyPWYFShKg5YUZW60V.jpg',
    categoryId3: 1445,
    goodsBriefEn: null,
    createTime: '2021-11-26 22:00:53',
    goodsPrice: 169.9,
    productList: [
      {
        productId: 39679460900954,
        specValues: '14 inches',
        goodsId: 6666753441882,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '44froclfsbob014',
        width: 0,
        warning: false,
        specValueIds: '14 inches',
        goodsName: '1B/27 Ombre Extented 4X4 Closure Lace Short Bob Wig',
        mainImageUrl: null,
        productPrice: 209.9,
        height: 0
      },
      {
        productId: 39679460868186,
        specValues: '12 inches',
        goodsId: 6666753441882,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '44froclfsbob012',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName: '1B/27 Ombre Extented 4X4 Closure Lace Short Bob Wig',
        mainImageUrl: null,
        productPrice: 189.9,
        height: 0
      },
      {
        productId: 39679460835418,
        specValues: '10 inches',
        goodsId: 6666753441882,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: '44froclfsbob010',
        width: 0,
        warning: false,
        specValueIds: '10 inches',
        goodsName: '1B/27 Ombre Extented 4X4 Closure Lace Short Bob Wig',
        mainImageUrl: null,
        productPrice: 169.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 424.75,
    goodsNameEn: null,
    goodsId: 6672817619034,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName: '1B/30 Ombre Brown Color Headband Wig | Throw On & Go',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39702738698330,
    categoryPath: 'Wigs->Weave Wigs->Headband Wig',
    goodsStock: 0,
    categoryId1: 1431,
    categoryId2: 1436,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/k8lzVYM4OkgtVqI1813.jpg',
    categoryId3: 1462,
    goodsBriefEn: null,
    createTime: '2021-12-14 19:09:06',
    goodsPrice: 169.9,
    productList: [
      {
        productId: 39702738698330,
        specValues: '18 inches',
        goodsId: 6672817619034,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 250,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: 'ombchbwwnbr018',
        width: 0,
        warning: false,
        specValueIds: '18 inches',
        goodsName: '1B/30 Ombre Brown Color Headband Wig | Throw On & Go',
        mainImageUrl: null,
        productPrice: 169.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 537.75,
    goodsNameEn: null,
    goodsId: 4507229749338,
    isVirtualGoods: 1,
    stateValue: '待售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 1,
    goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
    actualSales: 0,
    productStockWarningState: null,
    productId: 39276141772890,
    categoryPath: 'Wigs->Lace Wigs->13x4 Frontal Lace Wig',
    goodsStock: 0,
    categoryId1: 1431,
    categoryId2: 1435,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/3kaxWV9giwhrXZIG3t1.jpg',
    categoryId3: 1458,
    goodsBriefEn: null,
    createTime: '2020-01-10 16:43:01',
    goodsPrice: 214.9,
    productList: [
      {
        productId: 39276141772890,
        specValues: 'Straight,12 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 1,
        mainImage: null,
        productCode: '1b613fw1012',
        width: 0,
        warning: false,
        specValueIds: 'Straight,12 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 214.9,
        height: 0
      },
      {
        productId: 39276141576282,
        specValues: 'Straight,14 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw1014',
        width: 0,
        warning: false,
        specValueIds: 'Straight,14 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 224.9,
        height: 0
      },
      {
        productId: 31791072542810,
        specValues: 'Beach Wave,14 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw0914bw',
        width: 0,
        warning: false,
        specValueIds: 'Beach Wave,14 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 224.9,
        height: 0
      },
      {
        productId: 31791071985754,
        specValues: 'Beach Wave,26 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw0926bw',
        width: 0,
        warning: false,
        specValueIds: 'Beach Wave,26 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 349.9,
        height: 0
      },
      {
        productId: 31791070871642,
        specValues: 'Beach Wave,18 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw0918bw',
        width: 0,
        warning: false,
        specValueIds: 'Beach Wave,18 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 269.9,
        height: 0
      },
      {
        productId: 31791068315738,
        specValues: 'Beach Wave,16 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw0916bw',
        width: 0,
        warning: false,
        specValueIds: 'Beach Wave,16 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 244.9,
        height: 0
      },
      {
        productId: 31739288584282,
        specValues: 'Straight,20 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw1020',
        width: 0,
        warning: false,
        specValueIds: 'Straight,20 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 284.9,
        height: 0
      },
      {
        productId: 31739288551514,
        specValues: 'Straight,18 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw1018',
        width: 0,
        warning: false,
        specValueIds: 'Straight,18 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 269.9,
        height: 0
      },
      {
        productId: 31739288518746,
        specValues: 'Straight,16 inches',
        goodsId: 4507229749338,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 300,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '1b613fw1016',
        width: 0,
        warning: false,
        specValueIds: 'Straight,16 inches',
        goodsName: '1B/613 Blonde Celebrity Style 13x4 Frontal Lace Wig',
        mainImageUrl: null,
        productPrice: 244.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 92,
    goodsNameEn: null,
    goodsId: 241818402845,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 10,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
    actualSales: 16,
    productStockWarningState: null,
    productId: 3540882980893,
    categoryPath: 'Wigs->Hair HBundles->Hair Bundles',
    goodsStock: 5984,
    categoryId1: 1431,
    categoryId2: 1433,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/RuJmOs6ef0dEtIt2tr9.jpg',
    categoryId3: 1477,
    goodsBriefEn: null,
    createTime: '2017-10-25 17:34:36',
    goodsPrice: 56,
    productList: [
      {
        productId: 3540886913053,
        specValues: 'Kinky Curly,28 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 11,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11050',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,28 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 128.8,
        height: 0
      },
      {
        productId: 3540886814749,
        specValues: 'Kinky Curly,26 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 10,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11049',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,26 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 120.8,
        height: 0
      },
      {
        productId: 3540886585373,
        specValues: 'Kinky Curly,24 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 7,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11048',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,24 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 112.7,
        height: 0
      },
      {
        productId: 3540886487069,
        specValues: 'Kinky Curly,22 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 1,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11047',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,22 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 100.7,
        height: 0
      },
      {
        productId: 3540886388765,
        specValues: 'Kinky Curly,20 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11046',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,20 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 84.7,
        height: 0
      },
      {
        productId: 3540886290461,
        specValues: 'Kinky Curly,18 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11045',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,18 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 79.3,
        height: 0
      },
      {
        productId: 3540886224925,
        specValues: 'Kinky Curly,16 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11044',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,16 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 72.6,
        height: 0
      },
      {
        productId: 3540886126621,
        specValues: 'Kinky Curly,14 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11043',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,14 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 67.3,
        height: 0
      },
      {
        productId: 3540886028317,
        specValues: 'Kinky Curly,12 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11042',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,12 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 61.9,
        height: 0
      },
      {
        productId: 3540885962781,
        specValues: 'Kinky Curly,10 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 1,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11041',
        width: 0,
        warning: false,
        specValueIds: 'Kinky Curly,10 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 56,
        height: 0
      },
      {
        productId: 3540885897245,
        specValues: 'Big Curl,28 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 200,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11040',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,28 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 128.8,
        height: 0
      },
      {
        productId: 3540885798941,
        specValues: 'Big Curl,26 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 200,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11039',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,26 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 120.8,
        height: 0
      },
      {
        productId: 3540885733405,
        specValues: 'Big Curl,24 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 60,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11038',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,24 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 112.7,
        height: 0
      },
      {
        productId: 3540885635101,
        specValues: 'Big Curl,22 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 100,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11037',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,22 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 100.7,
        height: 0
      },
      {
        productId: 3540885569565,
        specValues: 'Big Curl,20 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 100,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11036',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,20 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 84.7,
        height: 0
      },
      {
        productId: 3540885504029,
        specValues: 'Big Curl,18 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 80,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11035',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,18 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 79.3,
        height: 0
      },
      {
        productId: 3540885372957,
        specValues: 'Big Curl,16 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 10,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11034',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,16 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 72.6,
        height: 0
      },
      {
        productId: 3540885274653,
        specValues: 'Big Curl,14 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 12,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11033',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,14 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 67.3,
        height: 0
      },
      {
        productId: 3540885209117,
        specValues: 'Big Curl,12 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 100,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11032',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,12 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 61.9,
        height: 0
      },
      {
        productId: 3540885110813,
        specValues: 'Big Curl,10 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 150,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11031',
        width: 0,
        warning: false,
        specValueIds: 'Big Curl,10 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 56,
        height: 0
      },
      {
        productId: 3540885045277,
        specValues: 'Deep Wave,28 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 60,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11030',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,28 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 128.8,
        height: 0
      },
      {
        productId: 3540884946973,
        specValues: 'Deep Wave,26 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 200,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11029',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,26 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 120.8,
        height: 0
      },
      {
        productId: 3540884848669,
        specValues: 'Deep Wave,24 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 261,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11028',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,24 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 112.7,
        height: 0
      },
      {
        productId: 3540884717597,
        specValues: 'Deep Wave,22 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 100,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11027',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,22 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 100.7,
        height: 0
      },
      {
        productId: 3540884652061,
        specValues: 'Deep Wave,20 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 260,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11026',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,20 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 84.7,
        height: 0
      },
      {
        productId: 3540884553757,
        specValues: 'Deep Wave,18 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 205,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11025',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,18 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 79.3,
        height: 0
      },
      {
        productId: 3540884455453,
        specValues: 'Deep Wave,16 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 200,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11024',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,16 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 72.6,
        height: 0
      },
      {
        productId: 3540884389917,
        specValues: 'Deep Wave,14 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 200,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11023',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,14 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 67.3,
        height: 0
      },
      {
        productId: 3540884291613,
        specValues: 'Deep Wave,12 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 100,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11022',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,12 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 61.9,
        height: 0
      },
      {
        productId: 3540884226077,
        specValues: 'Deep Wave,10 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 149,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11021',
        width: 0,
        warning: false,
        specValueIds: 'Deep Wave,10 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 56,
        height: 0
      },
      {
        productId: 3540884127773,
        specValues: 'Straight,28 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 39,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11020',
        width: 0,
        warning: false,
        specValueIds: 'Straight,28 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 128.8,
        height: 0
      },
      {
        productId: 3540884029469,
        specValues: 'Straight,26 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 100,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11019',
        width: 0,
        warning: false,
        specValueIds: 'Straight,26 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 120.8,
        height: 0
      },
      {
        productId: 3540883963933,
        specValues: 'Straight,24 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 98,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11018',
        width: 0,
        warning: false,
        specValueIds: 'Straight,24 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 112.7,
        height: 0
      },
      {
        productId: 3540883865629,
        specValues: 'Straight,22 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 100,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11017',
        width: 0,
        warning: false,
        specValueIds: 'Straight,22 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 100.7,
        height: 0
      },
      {
        productId: 3540883767325,
        specValues: 'Straight,20 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 199,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11016',
        width: 0,
        warning: false,
        specValueIds: 'Straight,20 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 84.7,
        height: 0
      },
      {
        productId: 3540883701789,
        specValues: 'Straight,18 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 200,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11015',
        width: 0,
        warning: false,
        specValueIds: 'Straight,18 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 79.3,
        height: 0
      },
      {
        productId: 3540883603485,
        specValues: 'Straight,16 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 200,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11014',
        width: 0,
        warning: false,
        specValueIds: 'Straight,16 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 72.6,
        height: 0
      },
      {
        productId: 3540883505181,
        specValues: 'Straight,14 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 500,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11013',
        width: 0,
        warning: false,
        specValueIds: 'Straight,14 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 67.3,
        height: 0
      },
      {
        productId: 3540883406877,
        specValues: 'Straight,12 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 245,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11012',
        width: 0,
        warning: false,
        specValueIds: 'Straight,12 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 61.9,
        height: 0
      },
      {
        productId: 3540883374109,
        specValues: 'Straight,10 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 70,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11011',
        width: 0,
        warning: false,
        specValueIds: 'Straight,10 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 56,
        height: 0
      },
      {
        productId: 3540883341341,
        specValues: 'Body Wave,28 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 142,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11010',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,28 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 128.8,
        height: 0
      },
      {
        productId: 3540883308573,
        specValues: 'Body Wave,26 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 135,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11009',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,26 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 120.8,
        height: 0
      },
      {
        productId: 3540883243037,
        specValues: 'Body Wave,24 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 142,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11008',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,24 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 112.7,
        height: 0
      },
      {
        productId: 3540883210269,
        specValues: 'Body Wave,22 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 140,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11007',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,22 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 100.7,
        height: 0
      },
      {
        productId: 3540883177501,
        specValues: 'Body Wave,20 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 77,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11006',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,20 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 84.7,
        height: 0
      },
      {
        productId: 3540883144733,
        specValues: 'Body Wave,18 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 184,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11005',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,18 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 79.3,
        height: 0
      },
      {
        productId: 3540883111965,
        specValues: 'Body Wave,16 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 157,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11004',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,16 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 72.6,
        height: 0
      },
      {
        productId: 3540883079197,
        specValues: 'Body Wave,14 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 178,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11003',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,14 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 67.3,
        height: 0
      },
      {
        productId: 3540883013661,
        specValues: 'Body Wave,12 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 182,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBAT11002',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,12 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 61.9,
        height: 0
      },
      {
        productId: 3540882980893,
        specValues: 'Body Wave,10 inches',
        goodsId: 241818402845,
        productStockWarning: -1,
        productStock: 119,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 1,
        mainImage: null,
        productCode: 'HBAT11001',
        width: 0,
        warning: false,
        specValueIds: 'Body Wave,10 inches',
        goodsName: '1Pc Best Virgin Human Hair Bundle All Textures',
        mainImageUrl: null,
        productPrice: 56,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 92,
    goodsNameEn: null,
    goodsId: 241876205597,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 10,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
    actualSales: 1,
    productStockWarningState: null,
    productId: 3542053421085,
    categoryPath: 'Wigs->Hair HBundles->Hair Bundles',
    goodsStock: 1024,
    categoryId1: 1431,
    categoryId2: 1433,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/ef0EAdEi9Wop6QLKoMm.jpg',
    categoryId3: 1477,
    goodsBriefEn: null,
    createTime: '2017-10-25 17:54:53',
    goodsPrice: 56,
    productList: [
      {
        productId: 3542054895645,
        specValues: '28 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 198,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11010',
        width: 0,
        warning: false,
        specValueIds: '28 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 128.8,
        height: 0
      },
      {
        productId: 3542054830109,
        specValues: '26 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 198,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11009',
        width: 0,
        warning: false,
        specValueIds: '26 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 120.8,
        height: 0
      },
      {
        productId: 3542054731805,
        specValues: '24 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 67,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11008',
        width: 0,
        warning: false,
        specValueIds: '24 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 112.7,
        height: 0
      },
      {
        productId: 3542054600733,
        specValues: '22 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 40,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11007',
        width: 0,
        warning: false,
        specValueIds: '22 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 100.7,
        height: 0
      },
      {
        productId: 3542054338589,
        specValues: '20 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 97,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11006',
        width: 0,
        warning: false,
        specValueIds: '20 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 84.7,
        height: 0
      },
      {
        productId: 3542054141981,
        specValues: '18 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 74,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11005',
        width: 0,
        warning: false,
        specValueIds: '18 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 79.3,
        height: 0
      },
      {
        productId: 3542053912605,
        specValues: '16 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 12,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11004',
        width: 0,
        warning: false,
        specValueIds: '16 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 72.6,
        height: 0
      },
      {
        productId: 3542053748765,
        specValues: '14 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 45,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11003',
        width: 0,
        warning: false,
        specValueIds: '14 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 67.3,
        height: 0
      },
      {
        productId: 3542053617693,
        specValues: '12 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 94,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: 'HBBC11002',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 61.9,
        height: 0
      },
      {
        productId: 3542053421085,
        specValues: '10 inches',
        goodsId: 241876205597,
        productStockWarning: -1,
        productStock: 199,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 1,
        mainImage: null,
        productCode: 'HBBC11001',
        width: 0,
        warning: false,
        specValueIds: '10 inches',
        goodsName: '1Pc Big Curl Best Virgin Human Hair Bundles',
        mainImageUrl: null,
        productPrice: 56,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 89.3,
    goodsNameEn: null,
    goodsId: 226918662173,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '1Pc Big Curl Lace Closure',
    actualSales: 0,
    productStockWarningState: null,
    productId: 3358219436061,
    categoryPath: 'Wigs->Closure & Frontal->4x4 Lace Closure',
    goodsStock: 99,
    categoryId1: 1431,
    categoryId2: 1438,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/jiJJF92BcJkruvqnp2x.jpg',
    categoryId3: 1483,
    goodsBriefEn: null,
    createTime: '2017-10-23 15:14:35',
    goodsPrice: 69.3,
    productList: [
      {
        productId: 3358219730973,
        specValues: '20 inches',
        goodsId: 226918662173,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LCBC06',
        width: 0,
        warning: false,
        specValueIds: '20 inches',
        goodsName: '1Pc Big Curl Lace Closure',
        mainImageUrl: null,
        productPrice: 104.4,
        height: 0
      },
      {
        productId: 3358219665437,
        specValues: '18 inches',
        goodsId: 226918662173,
        productStockWarning: -1,
        productStock: 21,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LCBC05',
        width: 0,
        warning: false,
        specValueIds: '18 inches',
        goodsName: '1Pc Big Curl Lace Closure',
        mainImageUrl: null,
        productPrice: 97.4,
        height: 0
      },
      {
        productId: 3358219599901,
        specValues: '16 inches',
        goodsId: 226918662173,
        productStockWarning: -1,
        productStock: 23,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LCBC04',
        width: 0,
        warning: false,
        specValueIds: '16 inches',
        goodsName: '1Pc Big Curl Lace Closure',
        mainImageUrl: null,
        productPrice: 89,
        height: 0
      },
      {
        productId: 3358219567133,
        specValues: '14 inches',
        goodsId: 226918662173,
        productStockWarning: -1,
        productStock: 26,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LCBC03',
        width: 0,
        warning: false,
        specValueIds: '14 inches',
        goodsName: '1Pc Big Curl Lace Closure',
        mainImageUrl: null,
        productPrice: 80.6,
        height: 0
      },
      {
        productId: 3358219501597,
        specValues: '12 inches',
        goodsId: 226918662173,
        productStockWarning: -1,
        productStock: 29,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LCBC02',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName: '1Pc Big Curl Lace Closure',
        mainImageUrl: null,
        productPrice: 77.8,
        height: 0
      },
      {
        productId: 3358219436061,
        specValues: '10 inches',
        goodsId: 226918662173,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 1,
        mainImage: null,
        productCode: '4x4LCBC01',
        width: 0,
        warning: false,
        specValueIds: '10 inches',
        goodsName: '1Pc Big Curl Lace Closure',
        mainImageUrl: null,
        productPrice: 69.3,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 336,
    goodsNameEn: null,
    goodsId: 227576610845,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
    actualSales: 0,
    productStockWarningState: null,
    productId: 3365055299613,
    categoryPath: 'Wigs->Closure & Frontal->13x4 Lace Frontal',
    goodsStock: 167,
    categoryId1: 1431,
    categoryId2: 1438,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/NeSb2KPcLLuhlRBpktC.jpg',
    categoryId3: 1481,
    goodsBriefEn: null,
    createTime: '2017-10-23 17:39:36',
    goodsPrice: 188,
    productList: [
      {
        productId: 39306759798874,
        specValues: '22 inches',
        goodsId: 227576610845,
        productStockWarning: -1,
        productStock: 114,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBC007',
        width: 0,
        warning: false,
        specValueIds: '22 inches',
        goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 275.5,
        height: 0
      },
      {
        productId: 3365055791133,
        specValues: '20 inches',
        goodsId: 227576610845,
        productStockWarning: -1,
        productStock: 16,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBC006',
        width: 0,
        warning: false,
        specValueIds: '20 inches',
        goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 251.5,
        height: 0
      },
      {
        productId: 3365055496221,
        specValues: '18 inches',
        goodsId: 227576610845,
        productStockWarning: -1,
        productStock: 17,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBC005',
        width: 0,
        warning: false,
        specValueIds: '18 inches',
        goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 220.5,
        height: 0
      },
      {
        productId: 3365055299613,
        specValues: '16 inches',
        goodsId: 227576610845,
        productStockWarning: -1,
        productStock: 20,
        length: 0,
        weight: 100,
        barCode: '',
        isDefault: 1,
        mainImage: null,
        productCode: '4x13LFBC004',
        width: 0,
        warning: false,
        specValueIds: '16 inches',
        goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 188,
        height: 0
      },
      {
        productId: 3365055037469,
        specValues: '14 inches',
        goodsId: 227576610845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBC003',
        width: 0,
        warning: false,
        specValueIds: '14 inches',
        goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 164.1,
        height: 0
      },
      {
        productId: 3365054709789,
        specValues: '12 inches',
        goodsId: 227576610845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBC002',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 151.3,
        height: 0
      },
      {
        productId: 3365054382109,
        specValues: '10 inches',
        goodsId: 227576610845,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBC001',
        width: 0,
        warning: false,
        specValueIds: '10 inches',
        goodsName: '1Pc Big Curl Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 142.9,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 218,
    goodsNameEn: null,
    goodsId: 226907095069,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '1Pc Body Wave Lace Closure',
    actualSales: 0,
    productStockWarningState: null,
    productId: 3357890445341,
    categoryPath: 'Wigs->Closure & Frontal->4x4 Lace Closure',
    goodsStock: 80,
    categoryId1: 1431,
    categoryId2: 1438,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/JemJqWLvwUNwQJivsQC.jpg',
    categoryId3: 1483,
    goodsBriefEn: null,
    createTime: '2017-10-23 15:04:13',
    goodsPrice: 139,
    productList: [
      {
        productId: 3357891035165,
        specValues: 'Three Part,20 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC18',
        width: 0,
        warning: false,
        specValueIds: 'Three Part,20 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 154.4,
        height: 0
      },
      {
        productId: 3357890969629,
        specValues: 'Three Part,18 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC17',
        width: 0,
        warning: false,
        specValueIds: 'Three Part,18 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 147.4,
        height: 0
      },
      {
        productId: 3357890904093,
        specValues: 'Three Part,16 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC16',
        width: 0,
        warning: false,
        specValueIds: 'Three Part,16 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 139,
        height: 0
      },
      {
        productId: 3357890838557,
        specValues: 'Three Part,14 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC15',
        width: 0,
        warning: false,
        specValueIds: 'Three Part,14 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 125.6,
        height: 0
      },
      {
        productId: 3357890773021,
        specValues: 'Three Part,12 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC14',
        width: 0,
        warning: false,
        specValueIds: 'Three Part,12 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 117.8,
        height: 0
      },
      {
        productId: 3357890707485,
        specValues: 'Three Part,10 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC13',
        width: 0,
        warning: false,
        specValueIds: 'Three Part,10 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 109.3,
        height: 0
      },
      {
        productId: 3357890609181,
        specValues: 'Free Part,20 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC12',
        width: 0,
        warning: false,
        specValueIds: 'Free Part,20 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 154.4,
        height: 0
      },
      {
        productId: 3357890543645,
        specValues: 'Free Part,18 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 80,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC11',
        width: 0,
        warning: false,
        specValueIds: 'Free Part,18 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 147.4,
        height: 0
      },
      {
        productId: 3357890445341,
        specValues: 'Free Part,16 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: '4x4LC10',
        width: 0,
        warning: false,
        specValueIds: 'Free Part,16 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 139,
        height: 0
      },
      {
        productId: 3357890379805,
        specValues: 'Free Part,14 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC09',
        width: 0,
        warning: false,
        specValueIds: 'Free Part,14 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 125.6,
        height: 0
      },
      {
        productId: 3357890314269,
        specValues: 'Free Part,12 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC08',
        width: 0,
        warning: false,
        specValueIds: 'Free Part,12 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 117.8,
        height: 0
      },
      {
        productId: 3357890215965,
        specValues: 'Free Part,10 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC07',
        width: 0,
        warning: false,
        specValueIds: 'Free Part,10 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 109.3,
        height: 0
      },
      {
        productId: 3357890150429,
        specValues: 'Middle Part,20 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC06',
        width: 0,
        warning: false,
        specValueIds: 'Middle Part,20 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 154.4,
        height: 0
      },
      {
        productId: 3357890084893,
        specValues: 'Middle Part,18 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC05',
        width: 0,
        warning: false,
        specValueIds: 'Middle Part,18 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 147.4,
        height: 0
      },
      {
        productId: 3357890052125,
        specValues: 'Middle Part,16 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC04',
        width: 0,
        warning: false,
        specValueIds: 'Middle Part,16 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 139,
        height: 0
      },
      {
        productId: 3357889986589,
        specValues: 'Middle Part,14 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC03',
        width: 0,
        warning: false,
        specValueIds: 'Middle Part,14 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 125.6,
        height: 0
      },
      {
        productId: 3357889921053,
        specValues: 'Middle Part,12 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC02',
        width: 0,
        warning: false,
        specValueIds: 'Middle Part,12 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 117.8,
        height: 0
      },
      {
        productId: 3357889789981,
        specValues: 'Middle Part,10 inches',
        goodsId: 226907095069,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x4LC01',
        width: 0,
        warning: false,
        specValueIds: 'Middle Part,10 inches',
        goodsName: '1Pc Body Wave Lace Closure',
        mainImageUrl: null,
        productPrice: 109.3,
        height: 0
      }
    ]
  },
  {
    isRecommend: 0,
    marketPrice: 336,
    goodsNameEn: null,
    goodsId: 227523231773,
    isVirtualGoods: 1,
    stateValue: '在售',
    categoryPathEn: null,
    isLock: 0,
    virtualSales: 0,
    warning: false,
    goodsBrief: '',
    state: 2,
    goodsName: '1Pc Body Wave Pre Plucked Lace Frontal',
    actualSales: 0,
    productStockWarningState: null,
    productId: 3364072259613,
    categoryPath: 'Wigs->Closure & Frontal->13x4 Lace Frontal',
    goodsStock: 91,
    categoryId1: 1431,
    categoryId2: 1438,
    mainImage:
      'http://oss-dev.htwig.com/images/seller/goods/202206/4PfAgpITN3jn3sUDIM8.jpg',
    categoryId3: 1481,
    goodsBriefEn: null,
    createTime: '2017-10-23 17:32:36',
    goodsPrice: 188,
    productList: [
      {
        productId: 3364072488989,
        specValues: '20 inches',
        goodsId: 227523231773,
        productStockWarning: -1,
        productStock: 19,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBW006',
        width: 0,
        warning: false,
        specValueIds: '20 inches',
        goodsName: '1Pc Body Wave Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 251.5,
        height: 0
      },
      {
        productId: 3364072325149,
        specValues: '18 inches',
        goodsId: 227523231773,
        productStockWarning: -1,
        productStock: 64,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBW005',
        width: 0,
        warning: false,
        specValueIds: '18 inches',
        goodsName: '1Pc Body Wave Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 220.5,
        height: 0
      },
      {
        productId: 3364072259613,
        specValues: '16 inches',
        goodsId: 227523231773,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 1,
        mainImage: null,
        productCode: '4x13LFBW004',
        width: 0,
        warning: false,
        specValueIds: '16 inches',
        goodsName: '1Pc Body Wave Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 188,
        height: 0
      },
      {
        productId: 3364072095773,
        specValues: '14 inches',
        goodsId: 227523231773,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBW003',
        width: 0,
        warning: false,
        specValueIds: '14 inches',
        goodsName: '1Pc Body Wave Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 164.1,
        height: 0
      },
      {
        productId: 3364071866397,
        specValues: '12 inches',
        goodsId: 227523231773,
        productStockWarning: -1,
        productStock: 8,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBW002',
        width: 0,
        warning: false,
        specValueIds: '12 inches',
        goodsName: '1Pc Body Wave Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 151.3,
        height: 0
      },
      {
        productId: 3364071800861,
        specValues: '10 inches',
        goodsId: 227523231773,
        productStockWarning: -1,
        productStock: 0,
        length: 0,
        weight: 100,
        barCode: null,
        isDefault: 0,
        mainImage: null,
        productCode: '4x13LFBW001',
        width: 0,
        warning: false,
        specValueIds: '10 inches',
        goodsName: '1Pc Body Wave Pre Plucked Lace Frontal',
        mainImageUrl: null,
        productPrice: 142.9,
        height: 0
      }
    ]
  }
]

const View = (props) => {
  const { setFun } = useStateClassOperate(rowOperate)
  const [columns] = useState(new TableData({ setFun }).data)
  const [showAddGoods, setShowAddGoods] = useState(false)
  const [dataSource, setDataSource] = useState([])
  const [selectedRows, setSelectedRows] = useState({})
  const [selectedRowKeys, setSelectedRowKeys] = useState([])

  useEffect(() => {
    const data = props.value || testData
    const selectedRowKeys = []
    const selectedRows = {}
    data.forEach((res) => {
      selectedRowKeys.push(res.goodsId)
      selectedRows[res.goodsId] = res
    })
    initSelectedRowData({ selectedRowKeys, selectedRows })
  }, [])

  function addGoodsOnOk(value) {
    initSelectedRowData(value)
  }

  function initSelectedRowData(value) {
    setSelectedRowKeys(clone(value.selectedRowKeys))
    const data = clone(value.selectedRows)
    const list = []
    const objectData = {}
    const dataLength = value.selectedRowKeys.length
    value.selectedRowKeys.forEach((res, index) => {
      list.push({ ...data[res], index: index + 1, dataLength })
      objectData[res] = data[res]
    })
    setSelectedRows(clone(objectData))
    setDataSource(clone(list))
  }

  function rowOperate(type, record) {
    const index = record.index
    const selectedRowKeys = dataSource.map((item) => item.goodsId)
    let data = ''
    switch (type) {
      case 'top':
        data = selectedRowKeys[index - 1]
        selectedRowKeys.splice(index - 1, 1)
        selectedRowKeys.unshift(data)
        break
      case 'up':
        data = selectedRowKeys[index - 2]
        selectedRowKeys[index - 2] = selectedRowKeys[index - 1]
        selectedRowKeys[index - 1] = data
        break
      case 'down':
        data = selectedRowKeys[index]
        selectedRowKeys[index] = selectedRowKeys[index - 1]
        selectedRowKeys[index - 1] = data
        break
      case 'delete':
        selectedRowKeys.splice(index - 1, 1)
        break
    }
    initSelectedRowData({ selectedRowKeys, selectedRows })
  }

  return (
    <div>
      <div>
        <Button>导出集合商品</Button>
        <Button>导入集合商品</Button>
        <Button
          onClick={() => {
            setShowAddGoods(true)
          }}
        >
          添加商品
        </Button>
      </div>
      <div>说明：大批量修改商品排序时，建议保存后导出集合商品，然后再导入</div>
      <Table
        columns={columns}
        dataSource={dataSource}
        pagination={{
          size: 'small',
          showSizeChanger: true,
          showQuickJumper: true,
          current: 1,
          pageSize: 10
        }}
        rowKey="goodsId"
        bordered
      />
      {showAddGoods && (
        <AddGoods
          onOk={addGoodsOnOk}
          selectedRows={selectedRows}
          selectedRowKeys={selectedRowKeys}
          onCancel={setShowAddGoods}
        />
      )}
    </div>
  )
}

export default View
